# Generated by Django 2.2.5 on 2019-09-21 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('row', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('wall_n', models.BooleanField(default=True)),
                ('wall_s', models.BooleanField(default=True)),
                ('wall_e', models.BooleanField(default=True)),
                ('wall_w', models.BooleanField(default=True)),
            ],
        ),
    ]
