# Generated by Django 2.2.5 on 2019-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lambdaMUD', '0003_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='column',
        ),
        migrations.RemoveField(
            model_name='player',
            name='row',
        ),
        migrations.AddField(
            model_name='player',
            name='currentRoom',
            field=models.IntegerField(default=0),
        ),
    ]
